# PSYC 5P02- Introduction to Programming for Psychology
## Fall 2025

### Midterm Hackathon
### October 23

* To compete this assignment, answer as many as the questions below as possible. You can answer the questions by modifying this Notebook or by creating a .py file. 

* ALL CODE MUST BE THOROUGHLY DOCUMENTED! You can use Notebook Markup or comments, but you must be detailed in your explanations of your code. Feel free to provide an explanation for your approach to solving a problem. 

* For each question, try to use the most efficient code you can to produce each response, unless otherwise specified. 

* All relevant files must be uploaded to a git repository that is shared with me (user: SMEmrich) in order for the midterm to be considered submitted. Please be sure to rename the file so it includes your name (e.g., JDoe-ProblemSet1.ipynb)

* NO AI/ChatGPT/allowed! You can use all course notes and past assignments. You can also use other sources, but only to explain a concept, not to produce the solution to a problem. If you get stuck, ask me and I will help walk you through what you're trying to do. 

* Try to focus on having working code rather than completing all sections (I’d rather you have Question 1 and 6 working then have Questions 1 - 6 but they’re all broken).


### Rubric:
* Accuracy & Efficiency: 50%
* Explaination and documentation: 50%

## Scenario:

You are analyzing data from a simple reaction-time experiment. Each question builds upon the previous one. The participant pressed a key when a visual target appeared. You’ll process and summarize their data using Python.

### Question 1

Using the ``random`` library, create a random number of trials (e.g., between 10 - 20) of rts that randomly vary between 450 and 700 ms.

Write some code that:

* Prints the number of trials "completed".
* Calculates and prints the mean and standard deviation of the reaction times.
* Prints the fastest and slowest reaction times.

(Feel free to use the ``statisics`` library or use ``numpy`` if you prefer)

In [64]:
import numpy as np

rng = np.random.default_rng() # random number generator 

n_trials = rng.integers(low=10, high=20) # rng.integers takes a range of values

trial_rts = rng.integers(low=450, high=700, size=(rand_n_trials))

# https://numpy.org/doc/2.1/reference/random/generated/numpy.random.Generator.integers.html


15

In [18]:
print('total trials completed =', n_trials)

total trials completed = 18


In [20]:
print(trial_rts)

[583 681 697 486 452 565 509 475 664 641 488 462 511 590 525]


In [29]:
mean = np.mean(trial_rts)

print('sample mean =', np.round(mean, 2))

# https://numpy.org/devdocs/reference/generated/numpy.mean.html

# I used the function np.round to print my values to 2 decimal points
# rounding: https://numpy.org/doc/2.1/reference/generated/numpy.round.html

trial mean = 555.27


In [27]:
sd = np.std(trial_rts)

print('sample sd =', np.round(sd, 2))

# https://numpy.org/devdocs/reference/generated/numpy.std.html


trial sd = 80.53


In [33]:
highest_rt = max(trial_rts) # takes the maximum value in a list

lowest_rt = min(trial_rts) # takes the minimum value in a list

print('highest sample rt =', highest_rt, '& lowest sample rt =', lowest_rt)

highest sample rt = 697 & lowest sample rt = 452


### Question 2

Using the same list rts from Question 1, write code that:

* Creates a new list called trimmed_rts that includes only trials below 600 ms.
* Prints the number of trials removed.
* Prints the new mean reaction time.

In [54]:
rt_cutoff = 600

trimmed_rts = trial_rts[(trial_rts < rt_cutoff)] # slices the trial_rts to only include rts below the rt_cutoff and stores them into new list

rt_removed = len(trial_rts) - len(trimmed_rts) # subtracts the len of original list to new list = diff between trials

new_mean = np.mean(trimmed_rts) # prints new mean
        

#cleaned_data = data[(data < sd_cut_above) & (data > sd_cut_below)]

681
697
664
641


In [43]:
trimmed_rts

array([583, 486, 452, 565, 509, 475, 488, 462, 511, 590, 525])

In [121]:
print("number of trials removed =", rt_removed)

number of trials removed = 4


In [123]:
print("new mean =", np.round(new_mean, 2))

new mean = 513.27


### Question 3 

Define a function called ``summarize_rts(rt_list)`` that:

* Takes a list of reaction times.
* Prints the number of trials, mean, and standard deviation.

Then:

* Call the function on both rts and trimmed_rts.

Compare the two means, printing a message such as:

``Trimmed data are faster by 25.4 ms``

In [133]:
def summarize_rts(rt_list):
    n_trials = len(rt_list)
    print('number of trials =', np.round(n_trials, 2))
    mean_rt = np.mean(rt_list)
    print('mean =', np.round(mean_rt, 2))
    sd_rt = np.std(rt_list)
    print('sd =', np.round(sd_rt, 2))

    return mean_rt

In [134]:
summarize_rts(trial_rts)

number of trials = 15
mean = 590.87
sd = 70.39


np.float64(590.8666666666667)

In [78]:
summarize_rts(trimmed_rts)

number of trials = 11
mean = 513.27
sd = 45.54


### Question 4

Write some code that that:

* Generates multiple subjects RTs within one variable (can be stored in a list, dictionary, or numpy array)

* Uses your summarize_rts() function to print each participant’s mean reaction time.

* Stores each participant’s mean in a list.

* Prints the group mean across all participants.


In [96]:
subjects = [101, 102, 103, 104, 105]


rng = np.random.default_rng()

n_trials = rng.integers(low=10, high=20)

trial_rts = rng.integers(low=450, high=700, size=(rand_n_trials))

subject_rts_first_try = [
    {"subject_id": 101, "rts": rng.integers(low=450, high=700, size=(rand_n_trials))},
    {"subject_id": 102, "rts": rng.integers(low=450, high=700, size=(rand_n_trials))},
    {"subject_id": 103, "rts": rng.integers(low=450, high=700, size=(rand_n_trials))},
    {"subject_id": 104, "rts": rng.integers(low=450, high=700, size=(rand_n_trials))},
    {"subject_id": 105, "rts": rng.integers(low=450, high=700, size=(rand_n_trials))}]


In [110]:
subject_rts = {
    "101":{"rts": rng.integers(low=450, high=700, size=(rand_n_trials))},
    "102":{"rts": rng.integers(low=450, high=700, size=(rand_n_trials))},
    "103":{"rts": rng.integers(low=450, high=700, size=(rand_n_trials))},
    "104":{"rts": rng.integers(low=450, high=700, size=(rand_n_trials))},
    "105":{"rts": rng.integers(low=450, high=700, size=(rand_n_trials))}}

# I fear I spent way too long trying to figure this out but this is the resources I was using https://www.w3schools.com/python/python_dictionaries_nested.asp

In [111]:
print(subject_rts["103"]["rts"])

[501 493 582 643 568 580 483 599 580 497 641 668 482 553 565]


In [140]:
summarize_rts(subject_rts["101"]["rts"])

# I was able to get this to work, such that I could apply the function I created to one participant in my dictionary.

# Overall, I think that I wanted to challenge myself but using a dictionary and I spent too much time trying to figure out how to actually access the
# values within the dictionary, that I wasted a bunch of time on it.


number of trials = 15
mean = 570.47
sd = 70.66


np.float64(570.4666666666667)

In [ ]:
subject_means = []

subject_means.append(sub_101[mean_rt]) # could not figure this out either, I tried to return the mean_rt but it was not letting me append to the list

### Question 5 

Create a class Participant that:

* Has attributes pid (ID) and rts (list of reaction times).

Includes methods:

* mean_rt() — returns the mean RT

* add_rt(rt) — adds a new RT

* num_trials() — returns how many trials they have

Then:

* Create an object for "S01" using the original data.

* Add a new reaction time of 505.

* Print the participant’s ID, number of trials, and updated mean.

In [151]:
class Participant:

    def __init__(self, ID, rts):
        self.pid = ID
        self.rts = rts
 # Define methods for the class
    def mean_rt(self):
        mean = np.mean(rts)
        print(mean)

    def add_rt(self):
        new_rt = ''

    def num_trials(self):
        n_trials = len()
        print(n_trials)

In [152]:
S01 = Participant("01", trial_rts)

S01

In [153]:
print(S01, S01.mean_rt)

<__main__.Participant object at 0x000001F488A39D30> <bound method Participant.mean_rt of <__main__.Participant object at 0x000001F488A39D30>>


### Question 6

You want to quickly simulate one trial of your reaction-time task in PsychoPy.

Write a minimal PsychoPy script that:

* Displays a fixation cross (+) for 1 second.

* Then displays the word "GO!" until a key is pressed.

* Records and prints the reaction time in milliseconds.

(Hint: Use from psychopy import visual, core, event; a win, Clock, and event.waitKeys().)